### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by parmdhillon** [lfre/next-preact#3]
I am getting this error, in production and development too. 
Error: Cannot find module 'webpack'
 code: 'MODULE_NOT_FOUND',

I've done changes in this codebase after installing dependencies

**Comment by lfre** [comment]
@parmdhillon Hi! Thank you for opening the issue. I created a CodeSandbox of the repo: 

Sandbox: https://codesandbox.io/p/github/lfre/next-13-preact/main
URL: https://7s2mt8-3000.csb.app/

It works w/o issues, so if you can share a sandbox that replicates the issue, that'd be great. Thanks!

**Comment by lfre** [comment]
Updated the repo/patches to work with Next 13.4.10 (latest as of this writing) and not seeing any issues for the demo. Re-open the issue with a reproducible example. Thanks!
